controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mecanum_controller:
      type: mecanum_controller/MecanumController

mecanum_controller:
  ros__parameters:
    publish_rate: 50.0 #Hz
    front_left_wheel_name: fl_wheel_joint 
    front_right_wheel_name: fr_wheel_joint
    rear_left_wheel_name: rl_wheel_joint
    rear_right_wheel_name: rr_wheel_joint

    wheel_separation_x: 1.56
    wheel_separation_y: 0.931

    wheel_separation_x_multiplier: 1.0
    wheel_separation_y_multiplier: 1.0

    wheel_radius: 0.203
    wheel_max_rotational_speed: 0.0 #ignored


    front_left_wheel_radius_multiplier: 1.0
    front_right_wheel_radius_multiplier: 1.0
    rear_left_wheel_radius_multiplier: 1.0
    rear_right_wheel_radius_multiplier: 1.0

    tf_frame_prefix_enable: true
    tf_frame_prefix: RTC_mecanum


    odom_frame_id: odom
    base_frame_id: base_footprint

    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    open_loop: false
    position_feedback: true
    enable_odom_tf: true
    cmd_vel_timeout: 0.5

    publish_limited_velocity: false
    velocity_rolling_window_size: 10
    use_stamped_vel: true

    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    linear.x.max_acceleration: 1.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    linear.y.has_velocity_limits: true
    linear.y.has_acceleration_limits: true
    linear.y.has_jerk_limits: false
    linear.y.max_velocity: 1.0
    linear.y.min_velocity: -1.0
    linear.y.max_acceleration: 1.0
    linear.y.max_jerk: 0.0
    linear.y.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0
    angular.z.max_acceleration: 1.0
    angular.z.min_acceleration: -1.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0
