controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mecanumbot_controller:
      type: mecanum_controller/MecanumController

mecanum_controller:
  ros__parameters:
    fl_wheel_joint_name: fl_wheel_joint
    fr_wheel_joint_name: fr_wheel_joint
    rl_wheel_joint_name: rl_wheel_joint
    rr_wheel_joint_name: rr_wheel_joint
    wheel_radius: 0.03
    wheel_distance:
      width: 0.46
      length: 0.40